version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./nginx/ssl/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
    depends_on:
      - backend
    networks:
      - backend-network

  backend:
    build: .
    ports:
      - "3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend-network
    restart: always

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge

